apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: online-shop-root-child        # Child app name
  namespace: argocd
spec:
  project: root-team
  source:
    repoURL: https://github.com/SanjanaMahapatra/argocd-demos.git
    targetRevision: main
    path: declarative_approach/online_shop
  destination:
    server: https://172.31.16.61:33893
    namespace: root
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
